/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/drive_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tuning-panel drive state with a fresh age_s field. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description drive_state.json plus an added age_s field. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DriveStatePayload"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newest flat capture with its current size and age. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Live capture status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveStatus"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incremental tail of an in-progress capture. */
        get: {
            parameters: {
                query?: {
                    /** @description Byte offset to resume from, or "end" for the aligned EOF. */
                    offset?: string;
                };
                header?: never;
                path: {
                    /** @description Capture file name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Capture tail slice. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live_tap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the live tap ring since a cycle counter. */
        get: {
            parameters: {
                query?: {
                    /** @description Only return cycles strictly newer than this counter. */
                    since_cycle?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Live tap snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status: "connecting";
                        } | {
                            reason: string;
                            /** @constant */
                            status: "unreachable";
                        } | {
                            counts_per_mm: number[];
                            /** Format: uint64 */
                            cycle_ns: number;
                            drive_names: string[];
                            drives?: {
                                [key: string]: {
                                    ferr: number[];
                                    pos: number[];
                                    target: number[];
                                    torque: number[];
                                };
                            };
                            first_cycle?: number | null;
                            /** Format: double */
                            fs_hz: number;
                            moving?: boolean[];
                            /** Format: uint64 */
                            next_cycle: number;
                            /** @constant */
                            status: "streaming";
                            /** Format: uint64 */
                            stride?: number;
                            timing: {
                                /** Format: uint32 */
                                late_frames: number;
                                /** Format: int32 */
                                lateness_ns: number;
                                /** Format: uint32 */
                                skips: number;
                            } | null;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This OpenAPI 3.1 document. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Run summaries, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunSummary"][];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a run directory and everything in it. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The deleted run name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze a run on demand, returning its results. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analysis results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Results"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw run manifest. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The run manifest, verbatim. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manifest"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or clear a run's note. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoteBody"];
                };
            };
            responses: {
                /** @description The stored note (empty when cleared). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-resolution toolpath for a run. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Toolpath steps. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunPath"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/plot_series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plot series for a run. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plot series. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlotSeries"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis results for a run. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analysis results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Results"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{name}/strain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strain map for a strain_map run. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run directory name. */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Strain map. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StrainMap"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccelResult: {
            present: boolean;
            psd_peaks: [
                number,
                number
            ][];
        };
        /** @description JSON error body: a single human-readable reason. */
        ApiError: {
            error: string;
        };
        Applied: {
            addr: string;
            servo: string;
            type: string;
            value: unknown;
        };
        Combined: {
            /** Format: double */
            cross_ferr_peak_mm: number;
            /** Format: double */
            on_ferr_peak_mm: number;
            /** Format: double */
            on_ferr_rms_mm: number;
        };
        DeleteResponse: {
            deleted: string;
        };
        DifferentialMode: {
            /** Format: double */
            coherence: number;
            /** Format: double */
            damping?: number | null;
            /** Format: double */
            freq_hz: number;
            /** Format: double */
            gain: number;
            /** Format: double */
            gain_db: number;
        };
        DifferentialResult: {
            modes: components["schemas"]["DifferentialMode"][];
            pair: string[];
            /** Format: uint */
            segments: number;
        };
        DriveResult: {
            metrics: components["schemas"]["Metrics"];
            psd_peaks: [
                number,
                number
            ][];
            resonance: components["schemas"]["Resonance"];
        };
        DriveStateParam: {
            addr: string;
            c_code: string;
            description: string;
            group: string;
            name: string;
            options?: {
                [key: string]: string;
            } | null;
            type: string;
            unit: string;
        };
        DriveStatePayload: {
            config_pins: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            created_utc: string;
            motors: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            params: components["schemas"]["DriveStateParam"][];
            slots: {
                [key: string]: number;
            };
            spatial?: components["schemas"]["SpatialFrame"] | null;
            /** Format: int64 */
            version: number;
        };
        LiveCapture: {
            /** Format: double */
            age_s?: number | null;
            name?: string | null;
            /** Format: uint64 */
            size_bytes: number;
        };
        LiveStatus: {
            capture?: components["schemas"]["LiveCapture"] | null;
        };
        /** @description Run manifest as written by the Python capture tooling: a typed view of the fields the dashboard reads, with additional producer fields permitted. */
        Manifest: {
            ambient?: components["schemas"]["ManifestAmbient"] | null;
            axis?: string | null;
            command?: string | null;
            experiment: string;
            motors?: components["schemas"]["ManifestMotor"][] | null;
            steps: components["schemas"]["ManifestStep"][];
            stroke_plan?: components["schemas"]["StrokePlan"] | null;
            tag?: string | null;
        };
        ManifestAmbient: {
            journal_params?: {
                [key: string]: {
                    [key: string]: number | string;
                };
            } | null;
            notches?: {
                [key: string]: {
                    [key: string]: components["schemas"]["NotchStateValue"];
                };
            } | null;
        };
        ManifestMotor: {
            counts_per_mm: number | null;
            name: string;
        };
        ManifestStep: {
            name: string;
            swept: {
                [key: string]: number;
            } | null;
        };
        Metrics: {
            /** Format: int64 */
            ferr_crosscheck_max: number;
            /** Format: int64 */
            ff_torque_offset_max?: number | null;
            /** Format: int64 */
            ff_velocity_offset_max?: number | null;
            moves: components["schemas"]["Move"][];
            /** Format: uint */
            samples: number;
            torque: components["schemas"]["TorqueSummary"];
            /** Format: double */
            torque_saturation_pct: number;
        };
        Move: {
            /** Format: int8 */
            direction: number;
            /** Format: double */
            end_ms: number;
            /** Format: double */
            ferr_mean_moving: number;
            /** Format: double */
            ferr_peak: number;
            /** Format: double */
            ferr_rms: number;
            /** Format: uint */
            move: number;
            /** Format: double */
            overshoot: number;
            /** Format: double */
            settle_ms?: number | null;
            settle_window_truncated: boolean;
            /** Format: double */
            start_ms: number;
        };
        NotchStateValue: {
            [key: string]: number | string;
        } | number | string;
        NoteBody: {
            note: string;
        };
        NoteResponse: {
            note: string;
        };
        PlotAccel: {
            magnitude: number[];
            t_s: number[];
        };
        PlotCombined: {
            cross_ferr_mm: number[];
            on_ferr_mm: number[];
        };
        PlotDifferential: {
            band: [
                number,
                number
            ];
            coherence: number[];
            /** Format: double */
            coherence_min: number;
            freq_hz: number[];
            mag_db: number[];
            modes: components["schemas"]["DifferentialMode"][];
            phase_deg: number[];
            torque_db: number[];
        };
        PlotDrive: {
            ferr_counts: number[];
            torque_per_mille: number[];
        };
        PlotPath: {
            act_x_mm: number[];
            act_y_mm: number[];
            cmd_x_mm: number[];
            cmd_y_mm: number[];
        };
        PlotPsd: {
            accel?: components["schemas"]["PlotPsdAccel"] | null;
            cartesian?: {
                [key: string]: number[];
            } | null;
            freq_hz: number[];
            per_drive: {
                [key: string]: number[];
            };
        };
        PlotPsdAccel: {
            freq_hz: number[];
            psd: number[];
            psd_x: number[];
            psd_y: number[];
            psd_z: number[];
        };
        PlotRingdown: {
            sources: components["schemas"]["PlotRingdownSource"][];
        };
        PlotRingdownSource: {
            /** Format: double */
            fs_hz: number;
            modes: components["schemas"]["RingdownMode"][];
            psd: number[];
            psd_freq_hz: number[];
            source: string;
            tails: components["schemas"]["PlotRingdownTail"][];
            unit: string;
        };
        PlotRingdownTail: {
            /** Format: double */
            start_s: number;
            value: number[];
        };
        PlotSeries: {
            steps: components["schemas"]["PlotStep"][];
            /** Format: int64 */
            version: number;
        };
        PlotStep: {
            accel?: components["schemas"]["PlotAccel"] | null;
            combined?: components["schemas"]["PlotCombined"] | null;
            differential?: components["schemas"]["PlotDifferential"] | null;
            drives: {
                [key: string]: components["schemas"]["PlotDrive"];
            };
            /** Format: double */
            fs_hz: number;
            moving: [
                number,
                number
            ][];
            name: string;
            /** @default null */
            path: components["schemas"]["PlotPath"] | null;
            psd: components["schemas"]["PlotPsd"];
            /** @default null */
            ringdown: components["schemas"]["PlotRingdown"] | null;
            /** Format: uint */
            stride: number;
            t_s: number[];
        };
        Resonance: {
            detected: boolean;
            /** Format: double */
            peak_hz: number;
            /** Format: double */
            ratio: number;
        };
        Results: {
            /** Format: double */
            fs_hz: number;
            /** Format: int64 */
            settle_band_counts: number;
            steps: components["schemas"]["StepResult"][];
            /** Format: int64 */
            torque_limit_per_mille: number;
            verdict: components["schemas"]["Verdict"];
            /** Format: int64 */
            version: number;
        };
        RingdownMode: {
            /** Format: double */
            amp: number;
            /** Format: double */
            cycles: number;
            /** Format: double */
            disp_um: number;
            /** Format: double */
            fit_start_ms: number;
            /** Format: double */
            freq_hz: number;
            /** Format: double */
            r2: number;
            /** Format: uint */
            tails: number;
            /** Format: double */
            zeta: number;
            /** Format: double */
            zeta_hi: number;
            /** Format: double */
            zeta_lo: number;
        };
        RingdownResult: {
            /** Format: double */
            guard_ms: number;
            sources: components["schemas"]["RingdownSource"][];
            /** Format: double */
            window_ms: number;
        };
        RingdownSource: {
            modes: components["schemas"]["RingdownMode"][];
            /** Format: double */
            noise_floor: number;
            source: string;
            /** Format: uint */
            tails: number;
            unit: string;
        };
        RunPath: {
            steps: components["schemas"]["RunPathStep"][];
            /** Format: int64 */
            version: number;
        };
        RunPathStep: {
            /** Format: uint */
            n_records: number;
            name: string;
            path: components["schemas"]["PlotPath"];
            truncated: boolean;
        };
        RunSummary: {
            axis?: string | null;
            experiment: string;
            has_results: boolean;
            mtime_utc: string;
            name: string;
            note?: string | null;
            tag: string;
            verdict?: components["schemas"]["VerdictSummary"] | null;
        };
        /**
         * @description Motor-space -> cartesian position map for the live spatial view, the
         *     SERVO_DUMP_TUNING mirror of `servo_strokes.spatial_frame`: `axes` are
         *     motor names (frame columns), each column folds the motor's invert sign
         *     in, so `mode_pos[k] = sum(frame[k][s] * drive_frame_pos_mm[s])`.
         */
        SpatialFrame: {
            axes: string[];
            frame: number[][];
            modes: string[];
        };
        StepResult: {
            accel?: components["schemas"]["AccelResult"] | null;
            combined?: components["schemas"]["Combined"] | null;
            differential?: components["schemas"]["DifferentialResult"] | null;
            drives: {
                [key: string]: components["schemas"]["DriveResult"];
            };
            flags: string[];
            name: string;
            /** @default null */
            ringdown: components["schemas"]["RingdownResult"] | null;
        };
        StrainBelt: {
            elastic: (number | null)[];
            friction: (number | null)[];
            pair: string;
        };
        StrainLine: {
            belts: components["schemas"]["StrainBelt"][];
            bin_centers: number[];
            name: string;
            swept: unknown;
        };
        StrainMap: {
            lines: components["schemas"]["StrainLine"][];
        };
        StrokePlan: {
            accel?: number | null;
            amplitude?: number | null;
            belt?: string | null;
            cruise_ms?: number | null;
            duration?: number | null;
            dwell_ms?: number | null;
            freq_end?: number | null;
            freq_start?: number | null;
            iterations?: number | null;
            line_spacing?: number | null;
            ramp?: number | null;
            speed?: number | null;
            speeds?: number[] | null;
            x_end?: number | null;
            x_start?: number | null;
            y_end?: number | null;
            y_start?: number | null;
            zero_sync?: boolean | null;
        };
        TorqueSummary: {
            /** Format: double */
            longest_burst_ms: number;
            /** Format: uint */
            moving_samples: number;
            /** Format: int64 */
            peak: number;
            /** Format: double */
            peak_pct_rated: number;
            rail_detected: boolean;
            /** Format: int64 */
            rail_level: number;
            /** Format: double */
            rail_ms: number;
            /** Format: double */
            rail_pct_moving: number;
            /** Format: uint */
            rail_samples: number;
        };
        Verdict: {
            apply?: components["schemas"]["Applied"][] | null;
            flags: string[];
            reason: string;
            recommended_step?: string | null;
        };
        VerdictSummary: {
            flags: string[];
            reason: string;
            recommended_step?: string | null;
        };
    };
    responses: {
        /** @description A query parameter or request body could not be parsed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The server failed to read, parse, or compute the response. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
